### ISSUE TITLE
Details about training

### ISSUE THREAD

**Issue by mmsr** [fangshuoz/ControlCity#1]
Hi, 
Thank you very much for sharing your amazing paper, inference code and weights in hugging face.
I have some  questions.
1.  Could you please provide more details about LoRA model? what is it trained on?
2.  Are you planning to share training code? 
3. Is the metadata supplied (apart from text prompt) is only (long,lat) coordinates? Could you please share your findings if you have tried any experiments without that?

thanks again

**Comment by fangshuoz** [comment]
Thank you very much for your interest in our work!

1. Regarding the LoRA training script for Stable Diffusion, you can easily find relevant resources on GitHub. The purpose of our LoRA model is to ensure that the generated images align well with the target domain.
2. Due to certain constraints, we are currently unable to share the training code. However, we are actively working towards making this possible in the future.
3. The provided metadata includes only the coordinates (latitude and longitude), which is specific to the task design.

I appreciate your questions and support!

**Comment by mmsr** [comment]
@fangshuoz I really appreciate how quickly you responded to my question. 
Using LoRA to align generated images with target domain is a good idea. Thanks for clarification.
